In [2]:
import pandas as pd 
import prince
import mca
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import statsmodels.api as sm
from sklearn.utils import resample

In [5]:
#SECTION 1: prep data for MCA explaining variation in telework/employment correlation
allcat = pd.read_csv('allcat.csv')
people_r = pd.read_csv('people.csv')
p_mca = people_r[['TUCASEID','TULINENO','CORR']]
p_mca['CORR'].describe()

count    276303.000000
mean          1.410021
std           0.491838
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max           2.000000
Name: CORR, dtype: float64

In [8]:
#resample dataset to 200,000 random samples, half CORR=1 and half CORR=2
cor = p_mca[p_mca['CORR'] == 1]
uncor = p_mca[p_mca['CORR'] == 2]

cor_r = resample(cor, replace=False, n_samples=100000, random_state=1)
uncor_r = resample(uncor, replace=False, n_samples=100000, random_state=1)

p_resampled = pd.concat([cor_r, uncor_r])
p_resampled

              TUCASEID  TULINENO  CORR
261901  20231007231568         3     1
272061  20231209231836         1     1
159609  20220101220694         1     1
24644   20190908190029         2     1
243634  20230604230590         1     1
...                ...       ...   ...
268823  20231109231436         1     2
235984  20230403231291         1     2
222916  20230201230554         2     2
129635  20210605212065         1     2
247636  20230704231625         1     2

[200000 rows x 3 columns]

In [11]:
#add other columns to remaining dataset
mcadf=p_resampled.merge(allcat, on=['TUCASEID','TULINENO'],how='left')
mcadf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 58 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   TUCASEID      200000 non-null  int64
 1   TULINENO      200000 non-null  int64
 2   CORR          200000 non-null  int64
 3   Unnamed: 0.2  200000 non-null  int64
 4   Unnamed: 0.1  200000 non-null  int64
 5   Unnamed: 0    200000 non-null  int64
 6   GEDIV         200000 non-null  int64
 7   GESTFIPS      200000 non-null  int64
 8   GTCBSA        200000 non-null  int64
 9   GTMETSTA      200000 non-null  int64
 10  HEHOUSUT      200000 non-null  int64
 11  HETENURE      200000 non-null  int64
 12  HRHTYPE       200000 non-null  int64
 13  HRYEAR4       200000 non-null  int64
 14  HUSPNISH      200000 non-null  int64
 15  PEABSRSN      200000 non-null  int64
 16  PEAFEVER      200000 non-null  int64
 17  PEAFNOW       200000 non-null  int64
 18  PEAFWHN1      200000 non-null  int64
 19  PEAFWHN2      200000 non-null  int64
 20  PEAFWHN3      200000 non-null  int64
 21  PEAFWHN4      200000 non-null  int64
 22  PECERT1       200000 non-null  int64
 23  PECERT2       200000 non-null  int64
 24  PECERT3       200000 non-null  int64
 25  PECYC         200000 non-null  int64
 26  PEDIPGED      200000 non-null  int64
 27  PEDISDRS      200000 non-null  int64
 28  PEDISEAR      200000 non-null  int64
 29  PEDISEYE      200000 non-null  int64
 30  PEDISOUT      200000 non-null  int64
 31  PEDISPHY      200000 non-null  int64
 32  PEDISREM      200000 non-null  int64
 33  PEDWRSN       200000 non-null  int64
 34  PEERNCOV      200000 non-null  int64
 35  PEERNHRY      200000 non-null  int64
 36  PEGR6COR      200000 non-null  int64
 37  PEGRPROF      200000 non-null  int64
 38  PEHGCOMP      200000 non-null  int64
 39  PEHSPNON      200000 non-null  int64
 40  PEMARITL      200000 non-null  int64
 41  PEMJNUM       200000 non-null  int64
 42  PEMJOT        200000 non-null  int64
 43  PEMLR         200000 non-null  int64
 44  PENATVTY      200000 non-null  int64
 45  PESEX         200000 non-null  int64
 46  PRCITSHP      200000 non-null  int64
 47  PRDASIAN      200000 non-null  int64
 48  PRDISFLG      200000 non-null  int64
 49  PRDTHSP       200000 non-null  int64
 50  PRMARSTA      200000 non-null  int64
 51  PTDTRACE      200000 non-null  int64
 52  PUAFEVER      200000 non-null  int64
 53  PUBUS1        200000 non-null  int64
 54  HRNUMHOU_c    200000 non-null  int64
 55  PRERNHLY_c    49966 non-null   float64
 56  PRNMCHLD_c    200000 non-null  int64
 57  PRTAGE_c      200000 non-null  int64
dtypes: float64(1), int64(57)
memory usage: 88.5 MB

In [14]:
#drop columns not relevant to assessing who is most likely to have correlated telework and emoloyment statuses
mcadf = mcadf.drop(['Unnamed: 0.1','Unnamed: 0','GTCBSA','HRYEAR4','PEAFWHN1','PEAFWHN2','PEAFWHN3','PEAFWHN4','PECERT2','PEDWRSN','PEGR6COR','PEHGCOMP','PEMJNUM','PEMLR','PENATVTY','PRDASIAN','PRDTHSP','PRMARSTA','PUAFEVER'], axis=1)
mcadf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 39 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   TUCASEID      200000 non-null  int64
 1   TULINENO      200000 non-null  int64
 2   CORR          200000 non-null  int64
 3   Unnamed: 0.2  200000 non-null  int64
 4   GEDIV         200000 non-null  int64
 5   GESTFIPS      200000 non-null  int64
 6   GTMETSTA      200000 non-null  int64
 7   HEHOUSUT      200000 non-null  int64
 8   HETENURE      200000 non-null  int64
 9   HRHTYPE       200000 non-null  int64
 10  HUSPNISH      200000 non-null  int64
 11  PEABSRSN      200000 non-null  int64
 12  PEAFEVER      200000 non-null  int64
 13  PEAFNOW       200000 non-null  int64
 14  PECERT1       200000 non-null  int64
 15  PECERT3       200000 non-null  int64
 16  PECYC         200000 non-null  int64
 17  PEDIPGED      200000 non-null  int64
 18  PEDISDRS      200000 non-null  int64
 19  PEDISEAR      200000 non-null  int64
 20  PEDISEYE      200000 non-null  int64
 21  PEDISOUT      200000 non-null  int64
 22  PEDISPHY      200000 non-null  int64
 23  PEDISREM      200000 non-null  int64
 24  PEERNCOV      200000 non-null  int64
 25  PEERNHRY      200000 non-null  int64
 26  PEGRPROF      200000 non-null  int64
 27  PEHSPNON      200000 non-null  int64
 28  PEMARITL      200000 non-null  int64
 29  PEMJOT        200000 non-null  int64
 30  PESEX         200000 non-null  int64
 31  PRCITSHP      200000 non-null  int64
 32  PRDISFLG      200000 non-null  int64
 33  PTDTRACE      200000 non-null  int64
 34  PUBUS1        200000 non-null  int64
 35  HRNUMHOU_c    200000 non-null  int64
 36  PRERNHLY_c    49966 non-null   float64
 37  PRNMCHLD_c    200000 non-null  int64
 38  PRTAGE_c      200000 non-null  int64
dtypes: float64(1), int64(38)
memory usage: 59.5 MB

In [17]:
mcadf.to_csv('thesis_mca_data.csv', header=True)

In [ ]:
#SECTION 2: run MCA

In [20]:
count = pd.read_table('thesis_mca_data.csv', sep=',', skiprows=0, index_col=0, header=0)
count = count.astype('category') 
print(count.shape)

(200000, 39)

In [29]:
#import cleaned dataset and drop na values
data = pd.read_table('thesis_mca_data.csv',
                     sep=',', skiprows=0, index_col=0, header=0)
data.dropna(inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49966 entries, 22 to 199998
Data columns (total 39 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TUCASEID      49966 non-null  int64
 1   TULINENO      49966 non-null  int64
 2   CORR          49966 non-null  int64
 3   Unnamed: 0.2  49966 non-null  int64
 4   GEDIV         49966 non-null  int64
 5   GESTFIPS      49966 non-null  int64
 6   GTMETSTA      49966 non-null  int64
 7   HEHOUSUT      49966 non-null  int64
 8   HETENURE      49966 non-null  int64
 9   HRHTYPE       49966 non-null  int64
 10  HUSPNISH      49966 non-null  int64
 11  PEABSRSN      49966 non-null  int64
 12  PEAFEVER      49966 non-null  int64
 13  PEAFNOW       49966 non-null  int64
 14  PECERT1       49966 non-null  int64
 15  PECERT3       49966 non-null  int64
 16  PECYC         49966 non-null  int64
 17  PEDIPGED      49966 non-null  int64
 18  PEDISDRS      49966 non-null  int64
 19  PEDISEAR      49966 non-null  int64
 20  PEDISEYE      49966 non-null  int64
 21  PEDISOUT      49966 non-null  int64
 22  PEDISPHY      49966 non-null  int64
 23  PEDISREM      49966 non-null  int64
 24  PEERNCOV      49966 non-null  int64
 25  PEERNHRY      49966 non-null  int64
 26  PEGRPROF      49966 non-null  int64
 27  PEHSPNON      49966 non-null  int64
 28  PEMARITL      49966 non-null  int64
 29  PEMJOT        49966 non-null  int64
 30  PESEX         49966 non-null  int64
 31  PRCITSHP      49966 non-null  int64
 32  PRDISFLG      49966 non-null  int64
 33  PTDTRACE      49966 non-null  int64
 34  PUBUS1        49966 non-null  int64
 35  HRNUMHOU_c    49966 non-null  int64
 36  PRERNHLY_c    49966 non-null  float64
 37  PRNMCHLD_c    49966 non-null  int64
 38  PRTAGE_c      49966 non-null  int64
dtypes: float64(1), int64(38)
memory usage: 15.2 MB

In [32]:
#remove id and target variables
X = data.drop(['CORR','TUCASEID','TULINENO','Unnamed: 0.2'], axis=1) 
cols_list = ['GEDIV', 'GESTFIPS', 'GTMETSTA', 'HEHOUSUT', 'HETENURE','HRHTYPE','HUSPNISH','PEABSRSN','PEAFEVER','PEAFNOW','PECERT1','PECERT3','PECYC','PEDIPGED','PEDISDRS','PEDISEAR','PEDISEYE','PEDISOUT','PEDISPHY','PEDISREM','PEERNCOV','PEERNHRY','PEGRPROF','PEHSPNOW','PEMARITL','PEMJOT','PESEX','PRCITSHP','PRDISFLG','PTDTRACE','PUBUS1','HRNUMHOU_c','PRERNHLY_c','PRNMCHLD_C','PRTAGE_C']
X.columns = cols_list
X.shape

(49966, 35)

In [35]:
mca = prince.MCA(
    n_components=3,
    n_iter=3,
    copy=True,
    check_input=True,
    engine='sklearn',
    random_state=42
)
mca = mca.fit(X) 
mca = mca.transform(X) 
print(mca)

               0         1         2
22     -0.252185  0.002019  0.186355
32     -0.041382  0.298247  0.096288
33      0.408711 -0.462776 -0.180358
37      0.032445 -0.313180 -0.106527
51      0.302937 -0.532547 -0.108100
...          ...       ...       ...
199993 -0.134394  0.028059  0.264853
199995 -0.063719 -0.077707  0.079825
199996 -0.594715  0.029257 -0.045213
199997 -0.028348 -0.125501 -0.128388
199998 -0.281759  0.096530  0.005697

[49966 rows x 3 columns]

In [41]:
#ran with different setting to find the number of components with significant eigenvalues
mca = prince.MCA(n_components=50)
mca = mca.fit(X)
eig = mca.eigenvalues_summary
#with 35 columns, any eigenvalue > 0.29 is significant

In [47]:
eig.to_csv('eig.csv', header=True)

In [ ]:
#SECTION 3; MCA results

In [50]:
mca.scree_plot()

/opt/conda/envs/anaconda-2024.02-py310/lib/python3.10/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [56]:
#mca for top 50 components
results = mca.column_coordinates(X)
results.to_csv('mca-results.csv', header=True)
results

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
GEDIV__1,-0.332859,0.084166,-0.029490,-0.978427,-0.184807,-1.491007,-0.455783,-0.538289,1.059034,-0.296889,...,0.030197,0.041114,-0.013568,-0.006899,0.037647,0.010507,-0.019759,-0.006870,-0.005699,0.026853
GEDIV__2,-0.042103,-0.066681,0.223854,-1.188843,0.579510,0.041794,-1.392190,-0.830981,0.879401,0.905578,...,-0.000757,-0.009830,-0.027702,0.007028,0.017458,-0.009297,-0.026175,-0.012799,0.005485,-0.000880
GEDIV__3,-0.337754,0.559762,-0.177937,0.182685,0.606899,-0.173228,-0.561609,0.307572,-1.862930,-0.495734,...,0.004688,0.022232,-0.003775,0.026419,0.028014,-0.012147,-0.002600,-0.017202,0.008310,-0.003296
GEDIV__4,-0.366609,0.672512,-0.411714,1.002868,1.324908,-0.484481,0.209334,1.143091,1.030083,1.228274,...,-0.007333,0.021253,-0.012089,0.031221,0.016262,0.010321,-0.014174,-0.020407,-0.002566,0.018036
GEDIV__5,0.322288,0.067060,-0.554300,-0.506451,-0.773744,0.920568,-0.066231,1.196249,0.446795,-0.596501,...,-0.015982,-0.028424,-0.015986,-0.044177,-0.045965,-0.004751,-0.008109,0.017656,0.007616,-0.021184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PRTAGE_C__3,-0.283363,-0.211976,0.041250,0.199908,-0.127458,0.141178,-0.000424,0.072655,0.027838,-0.002557,...,-0.072612,-0.048668,0.056424,-0.031690,-0.135405,-0.185828,0.145796,0.158839,-0.188014,-0.029739
PRTAGE_C__4,-0.422932,-0.158969,0.127490,0.102498,-0.170185,0.269272,-0.053560,0.009755,0.088144,-0.000775,...,-0.021567,0.231497,0.042551,0.121015,-0.005231,0.173898,-0.162637,0.046826,0.125583,0.024006
PRTAGE_C__5,-0.133652,0.232252,0.080882,-0.273240,0.003844,0.021594,0.076046,-0.113922,-0.015203,-0.003979,...,0.324457,-0.222253,-0.169468,-0.194781,0.222124,-0.005767,0.036715,-0.319389,0.127666,-0.149577
PRTAGE_C__6,0.054321,0.597152,0.088434,-0.410313,0.121391,-0.115109,0.129329,-0.151733,0.016959,0.118531,...,-0.387591,0.227315,0.195021,0.103879,-0.257275,-0.003943,-0.095921,0.300327,-0.190121,0.192995
PRTAGE_C__7,0.313385,0.992753,0.221316,-0.326403,0.020059,-0.081135,0.158855,-0.043622,0.067706,0.124096,...,0.198870,-0.263766,-0.152712,0.204329,0.441265,-0.147226,0.432001,-0.255522,0.036040,0.075184

In [97]:
for x in range (50):
    print('component ', x, ' variable coordinates >1')
    #print significant positive contributors
    print(results[x].loc[results[x] > 1])

component  0  variable coordinates >1
GESTFIPS__11    1.301584
HEHOUSUT__4     1.387042
HEHOUSUT__10    1.004765
HRHTYPE__10     1.387773
PEAFEVER__-1    1.161022
PEDISDRS__1     2.704788
PEDISEYE__1     1.561331
PEDISOUT__1     2.488779
PEDISPHY__1     1.498623
PEDISREM__1     1.725525
PRDISFLG__1     1.300654
PTDTRACE__12    2.245027
PTDTRACE__14    1.302883
PRTAGE_C__1     1.041965
Name: 0, dtype: float64
component  1  variable coordinates >1
PEDISDRS__1     5.046569
PEDISEAR__1     2.557346
PEDISEYE__1     2.503618
PEDISOUT__1     3.690004
PEDISPHY__1     2.949193
PEDISREM__1     2.599063
PRDISFLG__1     2.465037
PTDTRACE__14    1.377738
PTDTRACE__23    1.537576
Name: 1, dtype: float64
component  2  variable coordinates >1
GESTFIPS__15    1.152032
HEHOUSUT__4     1.506533
HEHOUSUT__12    1.078676
HRHTYPE__9      1.060090
PEABSRSN__12    1.229864
PEDISDRS__1     7.019173
PEDISEAR__1     2.898900
PEDISEYE__1     3.444364
PEDISOUT__1     5.423583
PEDISPHY__1     3.863628
PEDISREM__1     3.496489
PRDISFLG__1     3.144084
PTDTRACE__14    4.739324
PTDTRACE__15    1.070841
PTDTRACE__17    2.354750
PTDTRACE__23    2.584069
Name: 2, dtype: float64
component  3  variable coordinates >1
GEDIV__4         1.002868
GEDIV__8         1.187318
GESTFIPS__4      1.172035
GESTFIPS__8      1.088882
GESTFIPS__16     1.378427
GESTFIPS__19     1.127598
GESTFIPS__20     1.011688
GESTFIPS__30     1.376393
GESTFIPS__31     1.063780
GESTFIPS__35     1.214368
GESTFIPS__38     1.097390
GESTFIPS__40     1.187908
GESTFIPS__46     1.262697
GESTFIPS__49     1.403364
GESTFIPS__56     1.625115
GTMETSTA__3      1.641439
HEHOUSUT__10     4.823690
HEHOUSUT__12     4.755878
HRHTYPE__9       4.687494
HRHTYPE__10      5.233995
PEABSRSN__11     1.533311
PEAFEVER__-1     2.151379
PEDISDRS__1      1.414706
PEDISOUT__1      1.266349
PRNMCHLD_C__5    1.215297
PRTAGE_C__1      1.752299
Name: 3, dtype: float64
component  4  variable coordinates >1
GEDIV__4        1.324908
GESTFIPS__15    1.544085
GESTFIPS__19    1.365386
GESTFIPS__20    1.277069
GESTFIPS__27    1.360935
GESTFIPS__29    1.260097
GESTFIPS__31    1.313782
GESTFIPS__38    1.468368
GESTFIPS__46    1.367559
HEHOUSUT__4     1.416734
HEHOUSUT__7     1.012475
HEHOUSUT__10    6.420963
HEHOUSUT__12    7.807367
HRHTYPE__9      7.590389
HRHTYPE__10     7.722830
PEABSRSN__11    1.605833
PEABSRSN__12    1.701249
PEAFEVER__-1    2.247492
PTDTRACE__13    1.135585
PTDTRACE__14    1.374508
PTDTRACE__15    2.722702
PTDTRACE__21    1.257216
PRTAGE_C__1     1.876394
Name: 4, dtype: float64
component  5  variable coordinates >1
GEDIV__6        1.434142
GESTFIPS__1     1.460350
GESTFIPS__13    1.037907
GESTFIPS__21    1.445227
GESTFIPS__28    1.542150
GESTFIPS__47    1.350317
HRHTYPE__5      1.067449
PEABSRSN__6     1.039768
PEDISDRS__1     2.820705
PEDISOUT__1     1.885585
PEDISPHY__1     1.297316
PTDTRACE__14    2.162098
Name: 5, dtype: float64
component  6  variable coordinates >1
GEDIV__6         1.103872
GESTFIPS__1      1.145118
GESTFIPS__2      1.038835
GESTFIPS__15     1.294540
GESTFIPS__21     1.126147
GESTFIPS__28     1.158160
GESTFIPS__41     1.245564
GESTFIPS__47     1.026731
GESTFIPS__53     1.005428
HEHOUSUT__7      1.175556
HEHOUSUT__10    30.365792
HEHOUSUT__12    31.006691
HRHTYPE__8       1.292307
HRHTYPE__9      30.866070
HRHTYPE__10     31.209519
PEABSRSN__12     2.097620
PTDTRACE__15     4.299996
PTDTRACE__21     1.260927
PTDTRACE__26     1.659053
Name: 6, dtype: float64
component  7  variable coordinates >1
GEDIV__4         1.143091
GEDIV__5         1.196249
GESTFIPS__10     1.200416
GESTFIPS__11     1.231740
GESTFIPS__12     1.200088
GESTFIPS__13     1.207691
GESTFIPS__19     1.122642
GESTFIPS__20     1.106900
GESTFIPS__24     1.197381
GESTFIPS__27     1.162439
GESTFIPS__29     1.125472
GESTFIPS__31     1.101010
GESTFIPS__37     1.183017
GESTFIPS__38     1.468072
GESTFIPS__45     1.203293
GESTFIPS__46     1.110531
GESTFIPS__51     1.212313
GESTFIPS__54     1.090522
HEHOUSUT__10    13.394460
HEHOUSUT__12    16.157344
HRHTYPE__9      16.171367
HRHTYPE__10     13.310321
PEABSRSN__9      1.197342
PEABSRSN__11     1.071863
PEAFEVER__-1     1.596936
PTDTRACE__12     2.034241
PTDTRACE__15     1.007604
PRTAGE_C__1      1.302051
Name: 7, dtype: float64
component  8  variable coordinates >1
GEDIV__1        1.059034
GEDIV__4        1.030083
GESTFIPS__9     1.074520
GESTFIPS__19    1.013203
GESTFIPS__23    1.017054
GESTFIPS__25    1.066959
GESTFIPS__27    1.055401
GESTFIPS__29    1.010665
GESTFIPS__31    1.021738
GESTFIPS__33    1.048927
GESTFIPS__38    1.177741
GESTFIPS__44    1.023078
GESTFIPS__46    1.074762
GESTFIPS__50    1.046442
HEHOUSUT__10    9.467163
HEHOUSUT__12    8.219803
HRHTYPE__9      8.171152
HRHTYPE__10     9.759069
PEAFEVER__-1    1.000747
PEDISDRS__1     1.171298
PTDTRACE__23    1.875961
Name: 8, dtype: float64
component  9  variable coordinates >1
GEDIV__4         1.228274
GEDIV__7         1.653607
GESTFIPS__5      1.629478
GESTFIPS__19     1.199023
GESTFIPS__20     1.195548
GESTFIPS__22     1.616207
GESTFIPS__27     1.245157
GESTFIPS__29     1.205018
GESTFIPS__31     1.220203
GESTFIPS__38     1.525886
GESTFIPS__40     1.676358
GESTFIPS__46     1.227058
GESTFIPS__48     1.660955
HEHOUSUT__10    13.913819
HEHOUSUT__12    14.472125
HRHTYPE__9      14.283075
HRHTYPE__10     15.048119
Name: 9, dtype: float64
component  10  variable coordinates >1
GEDIV__2         1.453139
GEDIV__8         1.173579
GESTFIPS__4      1.249154
GESTFIPS__8      1.126528
GESTFIPS__16     1.098886
GESTFIPS__30     1.140888
GESTFIPS__32     1.170298
GESTFIPS__34     1.476720
GESTFIPS__35     1.210505
GESTFIPS__36     1.453543
GESTFIPS__42     1.438932
GESTFIPS__49     1.152593
GESTFIPS__56     1.085959
HEHOUSUT__10    17.574325
HEHOUSUT__12    18.312612
HRHTYPE__9      18.360505
HRHTYPE__10     17.286967
PTDTRACE__23     1.497459
Name: 10, dtype: float64
component  11  variable coordinates >1
GEDIV__1         1.853738
GESTFIPS__9      1.896039
GESTFIPS__23     1.690896
GESTFIPS__25     1.865553
GESTFIPS__33     1.860556
GESTFIPS__44     1.822743
GESTFIPS__50     1.820325
HEHOUSUT__10    40.731489
HEHOUSUT__12    40.278791
HRHTYPE__9      40.516749
HRHTYPE__10     39.303743
PEABSRSN__9      1.000493
PEDISDRS__1      1.101338
PTDTRACE__15     2.428842
PTDTRACE__17     1.000169
Name: 11, dtype: float64
component  12  variable coordinates >1
HEHOUSUT__10    3.167181
HEHOUSUT__12    2.088298
HRHTYPE__5      1.330922
HRHTYPE__8      1.158865
HRHTYPE__9      2.066400
HRHTYPE__10     3.298568
PEABSRSN__8     1.135942
PEABSRSN__11    4.498880
PEAFEVER__-1    6.541312
PEDISOUT__1     1.207104
PTDTRACE__8     1.198556
PTDTRACE__11    1.103649
PTDTRACE__14    3.398302
PTDTRACE__18    1.985032
PTDTRACE__19    1.691802
PTDTRACE__21    1.249842
PTDTRACE__23    2.377350
PRTAGE_C__1     5.247964
Name: 12, dtype: float64
component  13  variable coordinates >1
GESTFIPS__15    1.050927
PEABSRSN__11    5.240735
PEABSRSN__12    1.185040
PEAFEVER__-1    6.632665
PTDTRACE__8     1.033789
PTDTRACE__13    3.351084
PTDTRACE__15    1.901571
PUBUS1__1       1.541166
PUBUS1__2       1.626586
PRTAGE_C__1     5.255390
PRTAGE_C__7     1.004218
Name: 13, dtype: float64
component  14  variable coordinates >1
GESTFIPS__2     1.157243
GESTFIPS__40    1.306327
GESTFIPS__54    1.088356
GTMETSTA__3     1.363071
HEHOUSUT__3     2.188405
HEHOUSUT__4     1.998920
HEHOUSUT__10    2.643454
HRHTYPE__5      1.670265
HRHTYPE__6      1.023537
HRHTYPE__8      1.715185
HRHTYPE__10     2.189754
PEABSRSN__9     1.189152
PEABSRSN__11    1.547820
PEABSRSN__12    3.281150
PTDTRACE__9     1.271719
PTDTRACE__12    4.983130
PTDTRACE__14    4.067587
PTDTRACE__15    1.833598
PTDTRACE__26    2.435314
Name: 14, dtype: float64
component  15  variable coordinates >1
HEHOUSUT__4       1.482536
HEHOUSUT__10     14.136032
HRHTYPE__10      12.620497
PEABSRSN__10      1.950679
PRCITSHP__2       1.354488
PTDTRACE__12      1.634467
PRNMCHLD_C__4     1.864164
PRNMCHLD_C__5     1.381175
Name: 15, dtype: float64
component  16  variable coordinates >1
HEHOUSUT__10    20.109795
HRHTYPE__5       1.898632
HRHTYPE__10     20.902020
PEABSRSN__11     2.334271
PEABSRSN__12     3.108223
PTDTRACE__12     1.099682
PTDTRACE__17     1.908161
PTDTRACE__23     1.117116
Name: 16, dtype: float64
component  17  variable coordinates >1
HEHOUSUT__3      1.018746
HEHOUSUT__10    56.592978
HRHTYPE__2       1.325562
HRHTYPE__5       1.787113
HRHTYPE__10     56.528050
PEABSRSN__12     5.859212
PECYC__2         1.005467
PTDTRACE__10     1.053831
PTDTRACE__19     2.738678
PTDTRACE__21     1.924652
Name: 17, dtype: float64
component  18  variable coordinates >1
GESTFIPS__40     2.519127
GTMETSTA__3      3.216721
HEHOUSUT__7      1.226093
HEHOUSUT__10    91.763647
HRHTYPE__10     93.167513
PEABSRSN__6      1.159328
PTDTRACE__3      1.387548
PTDTRACE__14     1.300073
Name: 18, dtype: float64
component  19  variable coordinates >1
GESTFIPS__15      7.271106
GESTFIPS__22      1.044443
GESTFIPS__32      1.111728
HEHOUSUT__3       1.647608
HEHOUSUT__10     43.482025
HRHTYPE__10      43.122673
PEABSRSN__9       1.260024
PTDTRACE__4       1.020373
PTDTRACE__5       3.651916
PTDTRACE__8       1.817847
PTDTRACE__9       5.845913
PTDTRACE__15     12.325135
PTDTRACE__21     10.728408
PTDTRACE__26      9.292694
HRNUMHOU_c__6     1.426476
PRNMCHLD_C__5     1.384728
Name: 19, dtype: float64
component  20  variable coordinates >1
GESTFIPS__2      1.403680
GESTFIPS__5      1.258923
GESTFIPS__22     1.117652
GESTFIPS__23     1.850028
GESTFIPS__30     2.113730
GESTFIPS__33     1.743228
GESTFIPS__35     1.549215
GESTFIPS__41     1.086906
GESTFIPS__42     1.069186
GESTFIPS__50     2.783181
GESTFIPS__53     1.175189
GESTFIPS__54     1.429434
GESTFIPS__56     2.102504
HEHOUSUT__3      3.279690
HEHOUSUT__5      1.296940
HEHOUSUT__6      1.108016
HEHOUSUT__10    28.594219
HRHTYPE__10     27.555782
PEABSRSN__8      1.225416
PEABSRSN__9      2.330411
PEABSRSN__10     1.062118
PTDTRACE__13     2.983318
PTDTRACE__14     1.116974
PTDTRACE__18     2.513856
Name: 20, dtype: float64
component  21  variable coordinates >1
GESTFIPS__2      1.339487
GESTFIPS__15     2.179891
GESTFIPS__56     1.378227
HEHOUSUT__3      1.175079
HEHOUSUT__10    10.460344
HRHTYPE__10     11.008561
PEAFEVER__-1     1.375950
PEAFEVER__1      1.346969
PEMARITL__2      1.243575
PEMARITL__4      1.154561
PEMARITL__5      1.490232
PTDTRACE__5      1.406719
PTDTRACE__10     1.509609
PTDTRACE__12     3.252918
PTDTRACE__15     3.039420
PTDTRACE__21     3.802326
PTDTRACE__26     4.047780
Name: 21, dtype: float64
component  22  variable coordinates >1
GESTFIPS__15     1.178136
HEHOUSUT__3      1.682822
HEHOUSUT__4      3.935369
HEHOUSUT__12     1.070222
PEABSRSN__6      1.641647
PEABSRSN__12     3.904295
PRCITSHP__2      1.102712
PTDTRACE__9      1.232234
PTDTRACE__10     1.819254
PTDTRACE__13     3.353035
PTDTRACE__15     2.692395
PTDTRACE__19     1.453782
PTDTRACE__21     2.230497
PTDTRACE__26     3.650914
HRNUMHOU_c__5    2.536134
HRNUMHOU_c__6    4.092620
PRNMCHLD_C__5    8.731245
Name: 22, dtype: float64
component  23  variable coordinates >1
GESTFIPS__10      1.758932
HEHOUSUT__4       1.741915
HRHTYPE__5        1.410567
PEABSRSN__4       3.512863
PEABSRSN__5       2.217484
PEABSRSN__6       2.651411
PEABSRSN__7       2.570790
PEABSRSN__8       1.921613
PEABSRSN__9      16.312223
PEABSRSN__10      3.626647
PEABSRSN__14      5.304819
PTDTRACE__11      1.404640
PTDTRACE__19      1.741681
PUBUS1__2        12.264701
HRNUMHOU_c__5     1.573007
HRNUMHOU_c__6     1.881747
PRNMCHLD_C__5     5.166035
Name: 23, dtype: float64
component  24  variable coordinates >1
GESTFIPS__15     5.832674
GESTFIPS__35     1.264282
GESTFIPS__50     1.118515
PEABSRSN__4      1.069572
PEABSRSN__7      1.277665
PEABSRSN__9      6.539627
PEABSRSN__10     1.051620
PEABSRSN__11     3.501266
PEABSRSN__12     1.075674
PEABSRSN__14     1.251648
PRCITSHP__2      3.630940
PTDTRACE__5      3.210171
PTDTRACE__9      4.047132
PTDTRACE__15    13.706896
PTDTRACE__16     1.675620
PTDTRACE__18     1.042917
PTDTRACE__21     9.609168
PTDTRACE__26    16.229023
PUBUS1__2        3.164759
Name: 24, dtype: float64
component  25  variable coordinates >1
GESTFIPS__11     1.199340
GESTFIPS__41     1.200172
GESTFIPS__49     1.304992
HEHOUSUT__2      1.613991
HEHOUSUT__10     5.568889
HRHTYPE__10      2.804533
PEABSRSN__12     4.682245
PEDISDRS__1      1.459865
PRCITSHP__2      2.529584
PTDTRACE__5      2.283720
PTDTRACE__11     1.497572
PTDTRACE__12    10.775147
PTDTRACE__13     2.112183
PTDTRACE__15     2.679360
PTDTRACE__16     3.585880
PTDTRACE__17     4.531974
PTDTRACE__21     2.926491
PTDTRACE__23     4.386913
Name: 25, dtype: float64
component  26  variable coordinates >1
GESTFIPS__50     2.387178
GESTFIPS__56     2.287226
HEHOUSUT__3      8.390684
HEHOUSUT__4      5.977671
HRHTYPE__8       1.182333
PEABSRSN__6      1.356563
PEABSRSN__9      4.635211
PEDISDRS__1      9.473256
PEDISOUT__1      4.694501
PEDISPHY__1      1.513071
PTDTRACE__12     6.812898
PTDTRACE__13     3.684913
PTDTRACE__14    10.100584
PTDTRACE__17     3.035141
PTDTRACE__19     2.264599
PTDTRACE__23     1.257390
PUBUS1__2        1.079520
Name: 26, dtype: float64
component  27  variable coordinates >1
GESTFIPS__2     3.416428
GESTFIPS__8     1.028264
GESTFIPS__11    1.051928
GESTFIPS__23    1.701676
GESTFIPS__38    1.198792
GESTFIPS__51    1.150288
GESTFIPS__56    1.624759
HEHOUSUT__2     3.928911
HEHOUSUT__3     2.051787
HEHOUSUT__4     2.510888
HRHTYPE__2      3.909754
HRHTYPE__8      1.104544
PEABSRSN__6     3.426365
PEABSRSN__9     4.643510
PRCITSHP__3     1.850651
PTDTRACE__7     1.150081
PTDTRACE__8     2.235650
PTDTRACE__11    2.841422
PTDTRACE__12    6.265779
PTDTRACE__13    8.685288
PTDTRACE__14    3.418667
PTDTRACE__17    1.413922
Name: 27, dtype: float64
component  28  variable coordinates >1
GESTFIPS__2       2.659448
GESTFIPS__28      1.226512
GESTFIPS__35      3.469960
HRHTYPE__2        1.087529
HRHTYPE__8        2.473016
HRHTYPE__10       1.698493
PEABSRSN__6       3.843871
PEABSRSN__10      2.635929
PEABSRSN__11      3.050246
PEABSRSN__12      3.363626
PEDISDRS__1       2.124637
PTDTRACE__3       2.709932
PTDTRACE__6       1.220432
PTDTRACE__12     16.497402
PTDTRACE__13      3.584711
PTDTRACE__14      6.036981
PTDTRACE__15      3.036795
PTDTRACE__17      1.836403
PTDTRACE__18     14.321450
PTDTRACE__19      6.554655
PTDTRACE__21      3.199503
HRNUMHOU_c__6     1.027423
Name: 28, dtype: float64
component  29  variable coordinates >1
GESTFIPS__2       5.573802
GESTFIPS__35      1.970268
GESTFIPS__46      1.519807
HEHOUSUT__2       3.084760
HEHOUSUT__7       5.791157
HEHOUSUT__12      1.074791
HRHTYPE__2        2.666790
HRHTYPE__5        5.495998
HRHTYPE__9        1.178440
PEABSRSN__7       2.789805
PEABSRSN__11     12.055683
PEABSRSN__12      6.443504
PEDISDRS__1       2.348652
PEDISOUT__1       1.206869
PRCITSHP__2       2.771443
PRCITSHP__3       3.803040
PTDTRACE__3       1.402270
PTDTRACE__6       3.457705
PTDTRACE__8       2.733653
PTDTRACE__9       1.693257
PTDTRACE__12      6.100314
PTDTRACE__13     10.514898
PTDTRACE__14      5.393892
PTDTRACE__17      1.422697
PTDTRACE__18      5.153057
PTDTRACE__23      6.358634
PUBUS1__1         1.797678
HRNUMHOU_c__6     1.202930
PRNMCHLD_C__5     1.076186
Name: 29, dtype: float64
component  30  variable coordinates >1
GESTFIPS__2      1.642327
GESTFIPS__28     1.189554
GESTFIPS__46     1.229517
HEHOUSUT__3      3.555976
HRHTYPE__2       2.134575
PEABSRSN__11     6.371748
PEABSRSN__12    10.439607
PEDISEAR__1      1.406048
PEDISEYE__1      2.565436
PRCITSHP__2      1.053131
PTDTRACE__6      1.469133
PTDTRACE__8      1.364725
PTDTRACE__11     6.510491
PTDTRACE__12     1.584019
PTDTRACE__13    11.320220
PTDTRACE__14     5.128598
PTDTRACE__19     9.010064
PTDTRACE__21     2.105193
Name: 30, dtype: float64
component  31  variable coordinates >1
GESTFIPS__2       3.537573
GESTFIPS__10      1.584665
GESTFIPS__11      1.025820
GESTFIPS__20      1.126837
GESTFIPS__23      2.050779
GESTFIPS__24      1.279739
GESTFIPS__30      1.386410
GESTFIPS__50      1.736695
HEHOUSUT__2       3.121010
HEHOUSUT__3      10.632148
HRHTYPE__10       1.188667
PEABSRSN__11      4.100938
PEABSRSN__12     36.460132
PECERT3__2        1.564849
PEDISDRS__1       1.723255
PEERNCOV__1       1.180761
PEMARITL__2       1.007358
PEMJOT__1         1.372449
PTDTRACE__7       2.476437
PTDTRACE__10      3.269160
PTDTRACE__19     14.080015
PTDTRACE__26      9.603134
PUBUS1__1         2.183498
HRNUMHOU_c__6     2.525911
Name: 31, dtype: float64
component  32  variable coordinates >1
GESTFIPS__5       1.142701
GESTFIPS__9       1.045086
GESTFIPS__28      1.027152
GESTFIPS__30      1.975812
GESTFIPS__38      1.041202
GESTFIPS__56      1.216304
HEHOUSUT__3       2.507942
HEHOUSUT__7       8.199430
HETENURE__3       1.306538
HRHTYPE__8        2.120788
PEABSRSN__6       1.901156
PEABSRSN__9       6.955096
PEABSRSN__14      1.868445
PRCITSHP__2       2.853172
PTDTRACE__5       3.179495
PTDTRACE__12     13.605404
PTDTRACE__14      9.352538
PTDTRACE__16      2.286847
PTDTRACE__17      3.044921
PUBUS1__1         1.315253
HRNUMHOU_c__6     3.033462
Name: 32, dtype: float64
component  33  variable coordinates >1
GESTFIPS__2      1.790778
GESTFIPS__11     2.471683
GESTFIPS__23     1.365240
GESTFIPS__30     1.014227
GESTFIPS__31     1.088290
GESTFIPS__33     2.109571
GESTFIPS__41     1.035198
GESTFIPS__49     1.539765
GESTFIPS__54     1.118347
HEHOUSUT__3      7.382379
PEABSRSN__10     4.528728
PEABSRSN__12     2.712424
PEABSRSN__14     2.079966
PECYC__5         1.774121
PRCITSHP__3      2.818207
PTDTRACE__8      2.897785
PTDTRACE__9      1.871332
PTDTRACE__11     2.748829
PTDTRACE__12    18.706778
PTDTRACE__13    17.649622
PTDTRACE__14    10.843131
PTDTRACE__16     1.190063
PTDTRACE__17     3.411348
PTDTRACE__19    14.961658
Name: 33, dtype: float64
component  34  variable coordinates >1
GESTFIPS__10     1.819651
GESTFIPS__11     1.193524
GESTFIPS__23     1.909444
GESTFIPS__27     1.010402
GESTFIPS__34     1.113633
GESTFIPS__35     2.872393
HEHOUSUT__2      1.615378
HEHOUSUT__6      2.399797
HRHTYPE__5       6.338070
HRHTYPE__10      1.088809
PEABSRSN__4      1.427508
PEABSRSN__6      1.932894
PEABSRSN__7      1.165999
PEABSRSN__11    15.263031
PEABSRSN__12    16.558864
PECERT3__2       1.001158
PTDTRACE__3      1.127309
PTDTRACE__6      1.025421
PTDTRACE__9      1.351424
PTDTRACE__10     6.571104
PTDTRACE__11     2.447307
PTDTRACE__13     9.918554
PTDTRACE__14    12.077802
PTDTRACE__15     4.831489
PTDTRACE__16     1.059051
PUBUS1__2        1.071808
Name: 34, dtype: float64
component  35  variable coordinates >1
GESTFIPS__2      3.193049
GESTFIPS__11     2.508453
GESTFIPS__24     1.657806
GESTFIPS__30     2.127678
GESTFIPS__32     1.080427
GESTFIPS__54     2.188982
GESTFIPS__56     2.491688
HEHOUSUT__4      8.341944
HEHOUSUT__7      9.528149
PEABSRSN__7      1.749612
PTDTRACE__7      1.940140
PTDTRACE__9      1.053699
PTDTRACE__11     1.885292
PTDTRACE__13    21.819230
PTDTRACE__15     4.579390
PTDTRACE__17    10.816343
PTDTRACE__19     9.587456
PTDTRACE__23     3.761282
PUBUS1__1        2.913568
Name: 35, dtype: float64
component  36  variable coordinates >1
GESTFIPS__5      1.478218
GESTFIPS__19     1.128116
GESTFIPS__30     2.161492
GESTFIPS__44     1.471499
GESTFIPS__50     3.753631
GESTFIPS__51     1.049884
HEHOUSUT__3     25.489687
HEHOUSUT__4      1.286860
HEHOUSUT__10     1.442414
HRHTYPE__2       2.574766
HRHTYPE__5       4.202856
PEABSRSN__4      1.274591
PEABSRSN__10     4.122399
PEABSRSN__11     4.466233
PEERNCOV__1      2.089863
PTDTRACE__13    12.626550
PTDTRACE__14     1.627828
PTDTRACE__15     3.641183
PTDTRACE__18    18.290308
PTDTRACE__23    16.514366
PTDTRACE__26     1.175123
Name: 36, dtype: float64
component  37  variable coordinates >1
GESTFIPS__23     1.497424
GESTFIPS__24     1.039912
GESTFIPS__30     2.109413
GESTFIPS__35     1.133732
GESTFIPS__38     1.318119
GESTFIPS__44     1.880928
GESTFIPS__51     2.044035

In [9]:
#keep only coordinates >1 or <-1
sig_res = results[abs(results) > 1]
sig_res = sig_res.dropna(how='all', axis=1)
sig_res = sig_res.dropna(how='all', axis=0)
a_s_r = sig_res.transpose()
sig_res

NameError: name 'results' is not defined

In [68]:
list(a_s_r.columns)

['GEDIV__1',
 'GEDIV__2',
 'GEDIV__4',
 'GEDIV__5',
 'GEDIV__6',
 'GEDIV__7',
 'GEDIV__8',
 'GESTFIPS__1',
 'GESTFIPS__2',
 'GESTFIPS__4',
 'GESTFIPS__5',
 'GESTFIPS__8',
 'GESTFIPS__9',
 'GESTFIPS__10',
 'GESTFIPS__11',
 'GESTFIPS__12',
 'GESTFIPS__13',
 'GESTFIPS__15',
 'GESTFIPS__16',
 'GESTFIPS__17',
 'GESTFIPS__19',
 'GESTFIPS__20',
 'GESTFIPS__21',
 'GESTFIPS__22',
 'GESTFIPS__23',
 'GESTFIPS__24',
 'GESTFIPS__25',
 'GESTFIPS__26',
 'GESTFIPS__27',
 'GESTFIPS__28',
 'GESTFIPS__29',
 'GESTFIPS__30',
 'GESTFIPS__31',
 'GESTFIPS__32',
 'GESTFIPS__33',
 'GESTFIPS__34',
 'GESTFIPS__35',
 'GESTFIPS__36',
 'GESTFIPS__37',
 'GESTFIPS__38',
 'GESTFIPS__40',
 'GESTFIPS__41',
 'GESTFIPS__42',
 'GESTFIPS__44',
 'GESTFIPS__45',
 'GESTFIPS__46',
 'GESTFIPS__47',
 'GESTFIPS__48',
 'GESTFIPS__49',
 'GESTFIPS__50',
 'GESTFIPS__51',
 'GESTFIPS__53',
 'GESTFIPS__54',
 'GESTFIPS__55',
 'GESTFIPS__56',
 'GTMETSTA__3',
 'HEHOUSUT__2',
 'HEHOUSUT__3',
 'HEHOUSUT__4',
 'HEHOUSUT__5',
 'HEHOUSUT__6',
 'HEHOUSUT__7',
 'HEHOUSUT__10',
 'HEHOUSUT__12',
 'HETENURE__3',
 'HRHTYPE__2',
 'HRHTYPE__5',
 'HRHTYPE__6',
 'HRHTYPE__8',
 'HRHTYPE__9',
 'HRHTYPE__10',
 'PEABSRSN__4',
 'PEABSRSN__5',
 'PEABSRSN__6',
 'PEABSRSN__7',
 'PEABSRSN__8',
 'PEABSRSN__9',
 'PEABSRSN__10',
 'PEABSRSN__11',
 'PEABSRSN__12',
 'PEABSRSN__14',
 'PEAFEVER__-1',
 'PEAFEVER__1',
 'PECERT3__2',
 'PECYC__2',
 'PECYC__4',
 'PECYC__5',
 'PEDISDRS__1',
 'PEDISEAR__1',
 'PEDISEYE__1',
 'PEDISOUT__1',
 'PEDISPHY__1',
 'PEDISREM__1',
 'PEERNCOV__1',
 'PEMARITL__2',
 'PEMARITL__4',
 'PEMARITL__5',
 'PEMJOT__1',
 'PRCITSHP__2',
 'PRCITSHP__3',
 'PRDISFLG__1',
 'PTDTRACE__3',
 'PTDTRACE__4',
 'PTDTRACE__5',
 'PTDTRACE__6',
 'PTDTRACE__7',
 'PTDTRACE__8',
 'PTDTRACE__9',
 'PTDTRACE__10',
 'PTDTRACE__11',
 'PTDTRACE__12',
 'PTDTRACE__13',
 'PTDTRACE__14',
 'PTDTRACE__15',
 'PTDTRACE__16',
 'PTDTRACE__17',
 'PTDTRACE__18',
 'PTDTRACE__19',
 'PTDTRACE__21',
 'PTDTRACE__23',
 'PTDTRACE__26',
 'PUBUS1__1',
 'PUBUS1__2',
 'HRNUMHOU_c__5',
 'HRNUMHOU_c__6',
 'PRNMCHLD_C__4',
 'PRNMCHLD_C__5',
 'PRTAGE_C__1',
 'PRTAGE_C__7']

In [71]:
var = []
subcat = []

In [74]:
#determine which variables are positively correlated to CORR variable
for x in list(a_s_r.columns):
    y = str(x)
    z = y.split('__')[0]
    a = y.split('__')[1]
    var.append(z)
    subcat.append(a)

In [86]:
s_res['var'] = var
s_res['subcat'] = subcat
s_res

                      var subcat
GEDIV__1            GEDIV      1
GEDIV__2            GEDIV      2
GEDIV__4            GEDIV      4
GEDIV__5            GEDIV      5
GEDIV__6            GEDIV      6
...                   ...    ...
HRNUMHOU_c__6  HRNUMHOU_c      6
PRNMCHLD_C__4  PRNMCHLD_C      4
PRNMCHLD_C__5  PRNMCHLD_C      5
PRTAGE_C__1      PRTAGE_C      1
PRTAGE_C__7      PRTAGE_C      7

[129 rows x 2 columns]

In [89]:
s_res.loc[s_res['var'] == 'PRNMCHLD_C', 'var'] = 'PRNMCHLD_c'
s_res.loc[s_res['var'] == 'PRTAGE_C', 'var'] = 'PRTAGE_c'
s_res

                      var subcat
GEDIV__1            GEDIV      1
GEDIV__2            GEDIV      2
GEDIV__4            GEDIV      4
GEDIV__5            GEDIV      5
GEDIV__6            GEDIV      6
...                   ...    ...
HRNUMHOU_c__6  HRNUMHOU_c      6
PRNMCHLD_C__4  PRNMCHLD_c      4
PRNMCHLD_C__5  PRNMCHLD_c      5
PRTAGE_C__1      PRTAGE_c      1
PRTAGE_C__7      PRTAGE_c      7

[129 rows x 2 columns]